name: TMAS Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: code

      - name: Download TMAS CLI
        run: |
          curl -sL https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz | tar -xz
          chmod +x ./tmas
          ./tmas version

      - name: Run TMAS scan
        env:
          TMAS_API_KEY: ${{ secrets.TREND_KEY }}
        run: ./tmas scan dir:code -VS

