name: TMAS Docker Image Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tmas-docker-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t vulnerable-app:latest .

      - name: Save Docker image to tar file
        run: docker save -o vulnerable-app.tar vulnerable-app:latest

      - name: Download TMAS CLI
        run: |
          curl -sL https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz | tar -xz
          chmod +x ./tmas
          ./tmas version

      - name: Scan Docker image with TMAS
        env:
          TMAS_API_KEY: ${{ secrets.TREND_KEY }}
        run: ./tmas scan docker-archive:vulnerable-app.tar -VMS | tee scan-results.txt

      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: tmas-scan-results
          path: scan-results.txt

